import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { fetchContent } from 'utils/contentful';
import Joke from 'components/Joke';
import Header from 'components/Header';
import JokeProp from 'utils/contentTypes/Jokes';

type Props = {
  jokes: JokeProp[];
};

const Home: React.FC<Props> = ({ jokes }) => {
  return (
    <div className="bg-purple bg-opacity-100 h-screen overflow-y-scroll flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Header />
        <div>
          {jokes.map(({ content, sys }) => (
            <Joke key={sys.id} content={content} sys={sys} />
          ))}
        </div>
      </main>

      <footer className="text-center m-4">
        Built with ❤️ by{' '}
        <a rel="noreferrer" target="_blank" href="https://sammiepls.github.io">
          <span className="font-black">Sammie</span>
        </a>
        .
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const query = `query Jokes {
          jokeCollection {
            items {
              content
              sys {
                id
              }
            }
          }
        }`;

  const { jokeCollection } = await fetchContent(query);

  return {
    props: {
      jokes: jokeCollection.items,
    },
  };
};

export default Home;
