import Head from 'next/head';
import Image from 'next/image';
import { fetchContent } from 'utils/contentful';
import Joke from 'components/Joke';
import JokeProp from 'utils/contentTypes/Jokes';

type Props = {
  jokes: JokeProp[];
};

export default function Home({ jokes }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata"
          rel="stylesheet"
        />
      </Head>

      <main className="container">
        <h1>Welcome to my horrible jokes library</h1>

        <p>Yes I know they're terrible</p>
        <div>
          {jokes.map(({ content }) => (
            <Joke content={content} />
          ))}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const query = `query Jokes {
          jokeCollection {
            items {
              content
              sys {
                id
              }
            }
          }
        }`;

  const { jokeCollection } = await fetchContent(query);

  return {
    props: {
      jokes: jokeCollection.items,
    },
  };
}
